#   WHEEL > Config > Core
#   ---------------------
#
#   Routes for URL redirecting

# The fallback route, if no one match with the request
fallback:
	controller: 'error'
	action: '404'

# Path to the SASS compiler / css cache
'{filename}.css':
	sass: '{filename}.scss'

# All the routes ----------

'/':
	controller: 'index'
	action: 'index'

'/{c}[/]':
	controller: '{c}'
	action: 'index'

'/{c}/{a}[/]':
	controller: '{c}'
	action: '{a}'

'/{c}/{a}/{id}[/...]':
	controller: '{c}'
	action: '{a}'
	id: '{id}'